version: 2.1

orbs:
  cypress: cypress-io/cypress@1.16.1

references:
  default_env: &default_env
    docker:
      - image: cypress/base:12.14.0
    working_directory: ~/repo

  repo_cache_key_1: &repo_cache_key_1 v1-cypress-repo-{{ arch}}-{{ .Branch }}-{{ .Revision }}
  repo_cache_key_2: &repo_cache_key_2 v1-cypress-repo-{{ arch}}-{{ .Branch }}
  repo_cache_key_3: &repo_cache_key_3 v1-cypress-repo-{{ arch}}

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - *repo_cache_key_1
        - *repo_cache_key_2
        - *repo_cache_key_3

jobs:
  checkout_code:
    <<: *default_env
    steps:
      - *restore_repo
      - checkout
      - run: npx yarn@1.21.1 --production=false --frozen-lockfile
      - save_cache:
          key: *repo_cache_key_1
          paths:
            - .

  verify_formatting:
    <<: *default_env
    steps:
      - *restore_repo
      - run:
          name: Verify Prettier
          command: yarn prettier:verify

  verify_compile:
    <<: *default_env
    steps:
      - *restore_repo
      - run:
          name: Verify Typescript
          command: yarn compile

  verify_lint:
    <<: *default_env
    steps:
      - *restore_repo
      - run:
          name: Verify ESLint
          command: yarn lint --format junit --output-file /tmp/test-results/eslint.xml
      - store_test_results:
          path: /tmp/test-results

  tests:
    <<: *default_env
    parallelism: 4
    resource_class: large
    steps:
      - *restore_repo
      - run:
          name: Run test suite
          command: yarn test

workflows:
  version: 2
  test:
    jobs:
      - checkout_code
      - verify_compile:
          requires:
            - checkout_code
      - verify_lint:
          requires:
            - checkout_code
      - verify_formatting:
          requires:
            - checkout_code
      - tests:
          requires:
            - checkout_code
