name: Bug Report
description: Brief description of bug in Docs code/codebytes
title: "[Bug/Error] Subject : Entry Name(s)"
labels: ["bug"]
assignees: "Name(s) here"
body:
  - type: markdown
    attributes:
      value: Thanks for helping improve Codecademy Docs!
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Could you describe the behavior of the bug you are experiencing?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Could you describe what you were expecting?
      placeholder: Tell us what you see!
      value: "This was supposed to happen!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Other (not listed here)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Codecademy Doc's Code of Conduct
          required: true
  - type: checkboxes
    id: maintainers
    attributes:
      label: For Maintainers
      options:
        - label: Labels added
          required: true
        - label: Issue is assigned
          required: false