name: Entry/Term Request
description: Use this form to request 1-3 new entries/ terms for Docs.
title: "[Entry/Term Request]: Subject - Topic(s)"
body:
  - type: markdown
    attributes:
      value: "## Entry/Term Request \n
        Thanks for taking the time to tell us what Docs is missing!"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tells us what should be included in the new entries/terms.
      placeholder: Include link to relevant Docs subject (ex. JavaScript - https://www.codecademy.com/resources/docs/javascript)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: For Maintainers
      options:
        - label: Labels are added
        - label: Assignee(s) added
