name: New Entry/Term Request
description: Use this form to request 1-3 new entries/ terms for Docs.
title: "[Entry/Term Request]: "
labels: ["new entry", "good first issue"]
assignees: "List assignee(s) here"
body:
  - type: markdown
    attributes:
      value: "## Entry/Term Request"
      value: Thanks for taking the time to tell us what Docs is missing!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: For Maintainers
      options:
        - label: Labels are added
        - label: Assignee(s) added
