name: "Update concept of the week"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v1
        with:
          command: 'update-cotw'
      - name: 'Commit changes'
        run: |
          git add ./bin/concept-of-the-week.txt
          git commit -m "🤖 update concept of the week"
          git push

on:
  schedule:
    - cron: "0 13 * * 0" # every sunday at 1:00 pm UTC
